### ISSUE TITLE
Can it possibly be build and run on pocketbook ? 

### ISSUE THREAD

**Issue by diimdeep** [hwhw/kindlevncviewer#6]
Or there are too many dependencies on kindle stuff?
For example pocketbook 840:
    Linux 3.0.8
    ARMv7 Processor rev 2 (v7l)
    BogoMIPS    : 811.04
    Features    : swp half thumb fastmult vfp edsp neon vfpv3

**Comment by diimdeep** [comment]
https://github.com/koreader/koreader has been ported to pocketbook 840, it can be helpful.

**Comment by hwhw** [comment]
Yes, I know :-) Well, I don't have a PB, but as far as I can see, it shouldn't be too hard. Over the next 1-2 days, I wanted to get back coding on kvncviewer, so expect an update here soon.

**Comment by diimdeep** [comment]
I build it, tried to run and get `eink model not supported`

**Comment by hwhw** [comment]
Yep, all the changes that were made in Koreader would have to get ported over.

**Comment by hwhw** [comment]
Unfortunately, I never got to do this :-(
