### ISSUE TITLE
Publish binaries for K3

### ISSUE THREAD

**Issue by ARF1** [hwhw/kindlevncviewer#8]
I am a long time fan of the old kindlevncviewer. I love the idea of the hackable lua version and tried to install it on my K3.

Unfortunately the release published [on the forum](http://www.mobileread.com/forums/showthread.php?t=228167) is compiled for a different glibc version:

```
[root@kindle kvncviewer]# ./luajit vncviewer.lua
./luajit: /lib/libc.so.6: version `GLIBC_2.7' not found (required by ./luajit)
```

Is there any chance you could provide a K3 compatible binary release for the less tech-savy users?

**Comment by hwhw** [comment]
Oh crap, I really lost track on this project, sorry. I'll close this now, as I do not have enough resources (aka free time) to work on this (or provide binaries on a regular basis).
